controller.up.onEvent(ControllerButtonEvent.Pressed, function () {
    if (game_part == 1) {
        if (level > 1) {
            secerty_guard.setImage(img`
                ..............................
                ..............................
                ..............................
                ...........8888...............
                ..........885588..............
                .........88888888.............
                ..........444444..............
                ..........4f44f4..............
                ..........444444..............
                ..........44ff44..............
                ........8888888888............
                ........8886665888............
                ........8886666888............
                ........8888668888............
                ........8588668888............
                ..........88888888............
                ..........88..88..............
                ..........88..88..............
                ..........88..88..............
                ..............................
                ..............................
                ..............................
                ..............................
                ..............................
                ..............................
                ..............................
                ..............................
                ..............................
                ..............................
                ..............................
                `)
        }
    }
})
controller.down.onEvent(ControllerButtonEvent.Released, function () {
    if (game_part == 1) {
        if (level > 1) {
            secerty_guard.setImage(img`
                ..............................
                ..............................
                ..............................
                ...........8888...............
                ..........885588..............
                .........88888888.............
                ..........444444..............
                ..........4f44f4..............
                ..........444444..............
                ..........44ff44..............
                ........8888888888............
                ........8886665888............
                ........8886666888............
                ........8858668888............
                ........88f8668888............
                ..........888888..............
                ..........f8..88..............
                ..........88..88..............
                ..........88..88..............
                ..............................
                ..............................
                ..............................
                ..............................
                ..............................
                ..............................
                ..............................
                ..............................
                ..............................
                ..............................
                ..............................
                `)
        }
    }
})
controller.left.onEvent(ControllerButtonEvent.Pressed, function () {
    if (game_part == 1) {
        if (level > 1) {
            secerty_guard.setImage(img`
                ..............................
                ..............................
                ..............................
                ...........8888...............
                ..........885888..............
                .........88888888.............
                ..........444444..............
                ..........4f4f44..............
                ..........444444..............
                ..........44f444..............
                ........8888888888............
                ........8885668888............
                ........8886668888............
                ........8886688888............
                ......5fff86888888............
                ..........888888..............
                ..........88..88..............
                ..........88..88..............
                ..........88..88..............
                ..............................
                ..............................
                ..............................
                ..............................
                ..............................
                ..............................
                ..............................
                ..............................
                ..............................
                ..............................
                ..............................
                `)
        }
    }
})
controller.right.onEvent(ControllerButtonEvent.Released, function () {
    if (game_part == 1) {
        if (level > 1) {
            secerty_guard.setImage(img`
                ..............................
                ..............................
                ..............................
                ...........8888...............
                ..........885588..............
                .........88888888.............
                ..........444444..............
                ..........4f44f4..............
                ..........444444..............
                ..........44ff44..............
                ........8888888888............
                ........8886665888............
                ........8886666888............
                ........8858668888............
                ........88f8668888............
                ..........888888..............
                ..........f8..88..............
                ..........88..88..............
                ..........88..88..............
                ..............................
                ..............................
                ..............................
                ..............................
                ..............................
                ..............................
                ..............................
                ..............................
                ..............................
                ..............................
                ..............................
                `)
        }
    }
})
controller.left.onEvent(ControllerButtonEvent.Released, function () {
    if (game_part == 1) {
        if (level > 1) {
            secerty_guard.setImage(img`
                ..............................
                ..............................
                ..............................
                ...........8888...............
                ..........885588..............
                .........88888888.............
                ..........444444..............
                ..........4f44f4..............
                ..........444444..............
                ..........44ff44..............
                ........8888888888............
                ........8886665888............
                ........8886666888............
                ........8858668888............
                ........88f8668888............
                ..........888888..............
                ..........f8..88..............
                ..........88..88..............
                ..........88..88..............
                ..............................
                ..............................
                ..............................
                ..............................
                ..............................
                ..............................
                ..............................
                ..............................
                ..............................
                ..............................
                ..............................
                `)
        }
    }
})
controller.right.onEvent(ControllerButtonEvent.Pressed, function () {
    if (game_part == 1) {
        if (level > 1) {
            secerty_guard.setImage(img`
                ..............................
                ..............................
                ..............................
                ...........8888...............
                ..........888588..............
                .........88888888.............
                ..........444444..............
                ..........44f4f4..............
                ..........444444..............
                ..........444f44..............
                ........8888888888............
                ........8888665888............
                ........8888666888............
                ........8888866888............
                ........88888868fff5..........
                ..........888888..............
                ..........88..88..............
                ..........88..88..............
                ..........88..88..............
                ..............................
                ..............................
                ..............................
                ..............................
                ..............................
                ..............................
                ..............................
                ..............................
                ..............................
                ..............................
                ..............................
                `)
        }
    }
})
controller.up.onEvent(ControllerButtonEvent.Released, function () {
    if (game_part == 1) {
        if (level > 1) {
            secerty_guard.setImage(img`
                ..............................
                ..............................
                ..............................
                ...........8888...............
                ..........885588..............
                .........88888888.............
                ..........444444..............
                ..........4f44f4..............
                ..........444444..............
                ..........44ff44..............
                ........8888888888............
                ........8886665888............
                ........8886666888............
                ........8858668888............
                ........88f8668888............
                ..........888888..............
                ..........f8..88..............
                ..........88..88..............
                ..........88..88..............
                ..............................
                ..............................
                ..............................
                ..............................
                ..............................
                ..............................
                ..............................
                ..............................
                ..............................
                ..............................
                ..............................
                `)
        }
    }
})
controller.down.onEvent(ControllerButtonEvent.Pressed, function () {
    if (game_part == 1) {
        if (level > 1) {
            secerty_guard.setImage(img`
                ..............................
                ..............................
                ..............................
                ...........8888...............
                ..........885588..............
                .........88888888.............
                ..........444444..............
                ..........4f44f4..............
                ..........444444..............
                ..........44ff44..............
                ........8888888888............
                ........8886665888............
                ........8886666888............
                ........8888668888............
                ........8588668888............
                ..........888888..............
                ..........88..88..............
                ..........88..88..............
                ..........88..88..............
                ..............................
                ..............................
                ..............................
                ..............................
                ..............................
                ..............................
                ..............................
                ..............................
                ..............................
                ..............................
                ..............................
                `)
        }
    }
})
let secrty_guerd_prop: Sprite = null
let frooger_pop: Sprite = null
let kill = 0
let frogger: Sprite = null
let game_part = 0
let level = 0
let secerty_guard: Sprite = null
secerty_guard = sprites.create(img`
    ..............................
    ..............................
    ..............................
    ..............................
    ..............................
    ..............................
    ..........444444..............
    ..........4f44f4..............
    ..........444444..............
    ..........44ff44..............
    ........9999bb9999............
    ........9999bb9999............
    ........9999bb9999............
    ........9999999999............
    ........44ffeeff44............
    ..........888888..............
    ..........88..88..............
    ..........88..88..............
    ..........ff..ff..............
    ..............................
    ..............................
    ..............................
    ..............................
    ..............................
    ..............................
    ..............................
    ..............................
    ..............................
    ..............................
    ..............................
    `, SpriteKind.Player)
controller.moveSprite(secerty_guard)
game.showLongText("Five nights at frogers V0.9 ", DialogLayout.Bottom)
tiles.setTilemap(tilemap`level2`)
level = 0
scene.cameraFollowSprite(secerty_guard)
tiles.placeOnTile(secerty_guard, tiles.getTileLocation(1, 1))
game.showLongText("good morning", DialogLayout.Bottom)
let enerackt_button = sprites.create(img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . 5 5 5 5 5 . . . . . 
    . . . . . . 5 5 5 5 5 . . . . . 
    . . . . . . 5 5 5 5 5 . . . . . 
    . . . . . . 5 5 5 5 5 . . . . . 
    . . . . . . 5 5 5 5 5 . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    `, SpriteKind.Player)
tiles.placeOnTile(enerackt_button, tiles.getTileLocation(1, 9))
forever(function () {
    if (secerty_guard.overlapsWith(enerackt_button) && level == 0) {
        game.showLongText("new job at froggers pizzas", DialogLayout.Bottom)
        game_part = 1
        level = 1
        tiles.setTilemap(tilemap`level3`)
        tiles.placeOnTile(enerackt_button, tiles.getTileLocation(1, 17))
    }
    if (secerty_guard.overlapsWith(enerackt_button) && level == 1) {
        level = 2
        tiles.placeOnTile(enerackt_button, tiles.getTileLocation(8, 18))
    }
    if (secerty_guard.overlapsWith(enerackt_button) && level == 2) {
        game.showLongText("12:00 AM", DialogLayout.Bottom)
        frogger = sprites.create(img`
            ..............................
            ..............................
            .......777......777...........
            ......71117....71117..........
            ......71f17f77f71f17..........
            ......71117f77f71117..........
            .......777f7777f777...........
            .........f777777f.............
            .........77777777.............
            ........7777777777............
            .......77777ff77777...........
            .......772777777277...........
            ........7722222277............
            ..........777777..............
            ...........ffff...............
            ...........ffff...............
            .......77f777777f77...........
            .......77f777777f77...........
            .......77.777777.77...........
            .......777.ffff.777...........
            .......777.7777.777...........
            ...........ffff...............
            .........7f7777f7.............
            .........7f7777f7.............
            .........7ff77ff7.............
            .........77....77.............
            .........77....77.............
            .........77....77.............
            .........77....77.............
            ........777....777............
            `, SpriteKind.Enemy)
        tiles.placeOnTile(frogger, tiles.getTileLocation(12, 2))
        level = 3
        tiles.placeOnTile(enerackt_button, tiles.getTileLocation(1000, 18))
        pause(5000)
    }
    if (level == 3) {
        frogger.follow(secerty_guard)
        if (frogger.overlapsWith(secerty_guard)) {
            kill = 1
        }
    }
})
forever(function () {
    if (level == 3 && kill == 1) {
        secerty_guard.setImage(img`
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . 8 8 8 6 6 6 6 f 4 4 4 . 
            . . . 8 8 8 8 8 8 6 5 2 4 f 4 . 
            8 8 8 8 8 8 8 8 8 8 8 4 4 4 4 . 
            8 8 8 8 8 8 8 8 8 8 8 4 4 4 4 . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . 8 8 8 . . 
            . . . . . . . . . . . 8 8 8 8 . 
            . . . . . . . . . . . 8 5 8 8 . 
            . . . . . . . . . . . . 8 8 8 . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            `)
        pause(100)
        game.over(false)
    }
})
forever(function () {
    if (level == 3) {
        pause(20000)
        level = 4
        tiles.placeOnTile(frogger, tiles.getTileLocation(100000, 1000000))
        tiles.placeOnTile(secerty_guard, tiles.getTileLocation(12, 1))
    }
    if (level == 4) {
        game.showLongText("nights over lets go home", DialogLayout.Bottom)
        game.showLongText("time for bed", DialogLayout.Bottom)
        level = 5
    }
    if (level == 5) {
        game_part = 0
        tiles.setTilemap(tilemap`level4`)
        tiles.placeOnTile(enerackt_button, tiles.getTileLocation(1, 1))
    }
    if (level == 5 && secerty_guard.overlapsWith(enerackt_button)) {
        game.showLongText("goodnight", DialogLayout.Bottom)
        tiles.setTilemap(tilemap`level5`)
        secerty_guard.setImage(img`
            ..............................
            ..............................
            ..............................
            ..............................
            ..............................
            ..............................
            ..........444444..............
            ..........4f44f4..............
            ..........444444..............
            ..........44ff44..............
            ........9999bb9999............
            ........9999bb9999............
            ........9999bb9999............
            ........9999999999............
            ........44ffeeff44............
            ..........888888..............
            ..........88..88..............
            ..........88..88..............
            ..........ff..ff..............
            ..............................
            ..............................
            ..............................
            ..............................
            ..............................
            ..............................
            ..............................
            ..............................
            ..............................
            ..............................
            ..............................
            `)
        level = 6
        game.showLongText("next shift", DialogLayout.Bottom)
    }
    if (level == 6) {
        tiles.setTilemap(tilemap`level6`)
        tiles.placeOnTile(enerackt_button, tiles.getTileLocation(12, 1))
    }
    if (secerty_guard.overlapsWith(enerackt_button) && level == 6) {
        game.showLongText("(owo)                 Hey now the fun is beging", DialogLayout.Bottom)
        level = 7
        tiles.setTilemap(tilemap`level7`)
        tiles.placeOnTile(enerackt_button, tiles.getTileLocation(8, 18))
    }
    if (secerty_guard.overlapsWith(enerackt_button) && level == 7) {
        game.showLongText("powers off i need to turn it on", DialogLayout.Bottom)
        level = 8
        tiles.setTilemap(tilemap`level8`)
        tiles.placeOnTile(enerackt_button, tiles.getTileLocation(27, 1))
    }
    if (secerty_guard.overlapsWith(enerackt_button) && level == 8) {
        game.showLongText("Power on", DialogLayout.Bottom)
        level = 9
        tiles.setTilemap(tilemap`level9`)
        tiles.placeOnTile(enerackt_button, tiles.getTileLocation(27, 1))
        frooger_pop = sprites.create(img`
            ..............................
            ..............................
            .......777......777...........
            ......71117....71117..........
            ......71f17f77f71f17..........
            ......71117f77f71117..........
            .......777f7777f777...........
            .........f777777f.............
            .........77777777.............
            ........7777777777............
            .......77777ff77777...........
            .......772777777277...........
            ........7722222277............
            ..........777777..............
            ...........ffff...............
            ...........ffff...............
            .......77f777777f77...........
            .......77f777777f77...........
            .......77.777777.77...........
            .......777.ffff.777...........
            .......777.7777.777...........
            ...........ffff...............
            .........7f7777f7.............
            .........7f7777f7.............
            .........7ff77ff7.............
            .........77....77.............
            .........77....77.............
            .........77....77.............
            .........77....77.............
            ........777....777............
            `, SpriteKind.Enemy)
        tiles.placeOnTile(frooger_pop, tiles.getTileLocation(24, 3))
        game.showLongText("you wont get away this time", DialogLayout.Bottom)
        tiles.setTilemap(tilemap`level13`)
        tiles.placeOnTile(secerty_guard, tiles.getTileLocation(100000, 0))
        tiles.placeOnTile(frooger_pop, tiles.getTileLocation(100000, 0))
        tiles.placeOnTile(enerackt_button, tiles.getTileLocation(100000, 0))
        game_part = 0
        level = 10
    }
    if (secerty_guard.overlapsWith(enerackt_button) && level == 10) {
        game.showLongText("Power on", DialogLayout.Bottom)
        level = 11
        tiles.setTilemap(tilemap`level11`)
        tiles.placeOnTile(secerty_guard, tiles.getTileLocation(28, 24))
        tiles.placeOnTile(frooger_pop, tiles.getTileLocation(25, 24))
        secerty_guard.setImage(img`
            ...fff....fff...
            ...fef....fef...
            ...fffeeeefff...
            .....eeeeee.....
            .....efeefe.....
            .....eeeeee.....
            .....eeffee.....
            ...eeffeeffee...
            ...eefeffefee...
            ...eeffeeffee...
            ...eefeeeefee...
            ...efefeefefe...
            ...efeeffeefe...
            .....eeffee.....
            .....ef..fe.....
            .....fe..ef.....
            .....fe..ef.....
            .....ef..fe.....
            .....ef..fe.....
            `)
        game.showLongText("were am i?", DialogLayout.Bottom)
        level = 12
        game.showLongText("why am i brown", DialogLayout.Bottom)
        level = 13
        game.showLongText("(owo)                    You are now one of us.", DialogLayout.Bottom)
        level = 14
        game.showLongText("(ow0)                    Time to perform for the crowd. You are now known as teddy", DialogLayout.Bottom)
        level = 15
    }
    if (level == 15) {
        tiles.setTilemap(tilemap`level10`)
        secrty_guerd_prop = sprites.create(img`
            ...fff....fff...
            ...fef....fef...
            ...fffeeeefff...
            .....eeeeee.....
            .....efeefe.....
            .....eeeeee.....
            .....eeffee.....
            ...eeffeeffee...
            ...eefeffefee...
            ...eeffeeffee...
            ...eefeeeefee...
            ...efefeefefe...
            ...efeeffeefe...
            .....eeffee.....
            .....ef..fe.....
            .....fe..ef.....
            .....fe..ef.....
            .....ef..fe.....
            .....ef..fe.....
            `, SpriteKind.Player)
        tiles.placeOnTile(secerty_guard, tiles.getTileLocation(1000000, 2))
        tiles.placeOnTile(secrty_guerd_prop, tiles.getTileLocation(11, 2))
        tiles.placeOnTile(frooger_pop, tiles.getTileLocation(13, 2))
        scene.cameraFollowSprite(secrty_guerd_prop)
        pause(1000)
        tiles.setTilemap(tilemap`level15`)
        pause(1000)
        tiles.setTilemap(tilemap`level16`)
        pause(1000)
        tiles.setTilemap(tilemap`level17`)
        pause(1000)
        tiles.setTilemap(tilemap`level18`)
        pause(1000)
        tiles.setTilemap(tilemap`level19`)
        pause(1000)
        tiles.setTilemap(tilemap`level20`)
        level = 16
    }
    if (level == 16) {
        tiles.setTilemap(tilemap`level12`)
        tiles.placeOnTile(secerty_guard, tiles.getTileLocation(11, 2))
        tiles.placeOnTile(secrty_guerd_prop, tiles.getTileLocation(111111111, 2))
        tiles.placeOnTile(frooger_pop, tiles.getTileLocation(13, 2))
        scene.cameraFollowSprite(secerty_guard)
        game.showLongText("Where am I", DialogLayout.Bottom)
        level = 17
        game.showLongText("I need to get out of this suit", DialogLayout.Bottom)
        level = 18
        game.showLongText("(owo)                           If you try to get out that suit the wrong way You Will DIE", DialogLayout.Bottom)
        level = 19
        game.showLongText("I need to go to the repair room", DialogLayout.Bottom)
        level = 20
    }
    if (level == 20) {
        tiles.placeOnTile(enerackt_button, tiles.getTileLocation(27, 24))
        if (secerty_guard.overlapsWith(enerackt_button)) {
            secerty_guard.setImage(img`
                ................
                ................
                .....444444.....
                .....444444.....
                .....4f44f4.....
                .....444444.....
                .....44ff44.....
                ...eeffeeffee...
                ...eefeffefee...
                ...eeffeeffee...
                ...eefeeeefee...
                ...efefeefefe...
                ...efeeffeefe...
                .....eeffee.....
                .....ef..fe.....
                .....fe..ef.....
                .....fe..ef.....
                .....ef..fe.....
                .....ef..fe.....
                `)
            game.showLongText("yes", DialogLayout.Bottom)
            level = 21
            secerty_guard.setImage(img`
                ................
                ................
                .....444444.....
                .....444444.....
                .....4f44f4.....
                .....444444.....
                .....44ff44.....
                ...8888668888...
                ...8888665888...
                ...8888668888...
                ...8888668888...
                ...8888668888...
                ...8888888888...
                .....eeffee.....
                .....ef..fe.....
                .....fe..ef.....
                .....fe..ef.....
                .....ef..fe.....
                .....ef..fe.....
                `)
            game.showLongText("yes", DialogLayout.Bottom)
            level = 22
            secerty_guard.setImage(img`
                ................
                ................
                .....444444.....
                .....444444.....
                .....4f44f4.....
                .....444444.....
                .....44ff44.....
                ...8888668888...
                ...8888665888...
                ...8888668888...
                ...8888668888...
                ...8888668888...
                ...88ffefff88...
                .....888888.....
                .....88..88.....
                .....88..88.....
                .....88..88.....
                .....88..88.....
                .....88..88.....
                `)
            game.showLongText("now to escape", DialogLayout.Bottom)
            level = 23
            tiles.placeOnTile(enerackt_button, tiles.getTileLocation(4, 0))
            pause(500)
            tiles.placeOnTile(frogger, tiles.getTileLocation(27, 24))
            kill = 1
        }
    }
    if (level == 23) {
        if (secerty_guard.overlapsWith(enerackt_button)) {
            tiles.placeOnTile(frogger, tiles.getTileLocation(111111, 24))
            tiles.setTilemap(tilemap`level14`)
            tiles.placeOnTile(secerty_guard, tiles.getTileLocation(12, 1))
            game.showLongText("Im never going back there", DialogLayout.Bottom)
            level = 24
            game.over(true)
        }
    }
})
